In [14]:
# 2 x 3 - 20 x 3  = 2 x 20
import numpy as np

X = [[1,2,3],     # test: 2 x 3   
     [2,3,4]]
X = np.asarray(X)
Y = [[2,3,4],      
     [5,6,7]]
print(Y)

Y = np.tile(Y,(2,1))    # train: 4 x 3    
print(Y)
# X- Y = (2,20)
print(Y.shape)

[[2, 3, 4], [5, 6, 7]]
[[2 3 4]
 [5 6 7]
 [2 3 4]
 [5 6 7]]
(4, 3)


In [46]:
Z = [3,1,6,1,2,3]
Z = np.array(Z)
Z2 = [3,1,6,4,2,5]
# kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
sortedDistIndicies = Z.argsort(kind = 'heapsort')   
print('sortedDistIndicies', sortedDistIndicies)                               # ndarray(3,)     # list

Z2 = np.array(Z2)
z2sort = Z2.argsort()   
print('z2sort', z2sort)  

sortedDistIndicies [3 1 4 0 5 2]
z2sort [1 4 0 3 5 2]


In [47]:
x = np.array([[0, 3, 1], 
              [2, 1, 5],
              [3, 2, 4]])
x2 = np.argsort(x, axis=0)                  #按 列 排序
print(x2)


[[0 1 0]
 [1 2 2]
 [2 0 1]]
