In [104]:
# exceplictly one loop
import numpy as np
# Y.row / X.row must be interger
X = [[1,2,3],       # 3 x 3
     [2,3,4],
     [1,2,1]]
Y = [[2,3,4],       
     [4,5,6],
     [2,3,4]]
Y = np.tile(Y,(2,1))    # 6 x 3
X = np.array(X)
dists = np.zeros((3,6))
for i in range(3):
    X_piece = X[i]
    X_piece = np.tile(X_piece,(6,1))
    diff1 = ((X_piece - Y)**2).sum(axis=1)
    diff1 = np.sqrt(diff1)
    dists[i,:] = diff1
print(dists)

[[1.73205081 5.19615242 1.73205081 1.73205081 5.19615242 1.73205081]
 [0.         3.46410162 0.         0.         3.46410162 0.        ]
 [3.31662479 6.55743852 3.31662479 3.31662479 6.55743852 3.31662479]]


In [ ]:
A = np.sum(X**2, axis=1)
B = np.sum(Y**2, axis=1)

In [121]:
import numpy as np
A = np.array([29, 77, 29, 29, 77, 29])
B = np.array([14 ,29  ,6])
A1 = A.reshape(1,6)
B1 = B.reshape(3,1)
C = A1 + B1 
D = np.dot(X,Y.T)
print(C)
print(D)
E = C- 2* D
E = np.sqrt(E)
print(E)

[[ 43  91  43  43  91  43]
 [ 58 106  58  58 106  58]
 [ 35  83  35  35  83  35]]
[[20 32 20 20 32 20]
 [29 47 29 29 47 29]
 [12 20 12 12 20 12]]
[[1.73205081 5.19615242 1.73205081 1.73205081 5.19615242 1.73205081]
 [0.         3.46410162 0.         0.         3.46410162 0.        ]
 [3.31662479 6.55743852 3.31662479 3.31662479 6.55743852 3.31662479]]


In [130]:
X = np.array([[1,2],[2,3]]).reshape(2,2)
Y = np.array([[2,4,5],[1,2,1]]).reshape(2,3)
print(np.dot(X,Y))
# print(np.matmul(X*Y))

[[ 4  8  7]
 [ 7 14 13]]


In [129]:
a = [[1,0],
     [0,1]] 
b = [1,2]
print (np.matmul(b,a))

[1 2]
