In [39]:
# exceplictly one loop
import numpy as np
# Y.row / X.row must be interger
X = [[1,2,3],       # 3 x 3
     [2,3,4],
     [1,2,1]]
Y = [[2,3,4],       
     [4,5,6],
     [2,3,4]]
Y = np.tile(Y,(2,1))    # 6 x 3
X = np.array(X)
dists = np.zeros((3,6))
for i in range(3):
    X_piece = X[i]
    X_piece = np.tile(X_piece,(6,1))
    diff1 = ((X_piece - Y)**2).sum(axis=1)
    # diff2 = diff1.sum(axis= 1)
    dists[i,:] = diff1
print(dists)

[[ 3. 27.  3.  3. 27.  3.]
 [ 0. 12.  0.  0. 12.  0.]
 [11. 43. 11. 11. 43. 11.]]


$$A=
\left[
 \begin{matrix}
   X_{1,1}^2 & X & X\\
   2 & 3 & 4\\
   1 & 2 & 1
  \end{matrix} 
\right ]
$$


In [48]:
temp1 = Y**2
temp2 = np.sum(temp1,axis=1)
temp3 = temp2.reshape(1,6)
print(Y)
print(temp2.shape, temp2)
print(temp3.shape,temp3)

[[ 4  9 16]
 [16 25 36]
 [ 4  9 16]
 [ 4  9 16]
 [16 25 36]
 [ 4  9 16]]
(6,) [ 353 2177  353  353 2177  353]
(1, 6) [[ 353 2177  353  353 2177  353]]


In [35]:
dists += np.sum(Y ** 2, axis=1).reshape(1, 6)
dists = np.around(dists)
print('1st dists: ', dists)
dists += np.sum(X ** 2, axis=1).reshape(3, 1)
dists = np.around(dists)
print('2nd dists: ', dists)
dists -= 2 * np.dot(X, Y.T)
dists = np.around(dists)
print('3rd dists: ', dists)
dists = np.sqrt(dists)
dists = np.around(dists)
print('4th dists: ', dists)

1st dists:  [[31. 83. 31. 31. 83. 31.]
 [29. 81. 29. 29. 81. 29.]
 [33. 84. 33. 33. 84. 33.]]
2nd dists:  [[ 45.  97.  45.  45.  97.  45.]
 [ 58. 110.  58.  58. 110.  58.]
 [ 39.  90.  39.  39.  90.  39.]]
3rd dists:  [[ 5. 33.  5.  5. 33.  5.]
 [ 0. 16.  0.  0. 16.  0.]
 [15. 50. 15. 15. 50. 15.]]
4th dists:  [[2. 6. 2. 2. 6. 2.]
 [0. 4. 0. 0. 4. 0.]
 [4. 7. 4. 4. 7. 4.]]


In [ ]:
import numpy as np
dists +=  np.sum(self.X_train ** 2, axis=1).reshape(1, num_train)
dists += np.sum(X ** 2, axis=1).reshape(num_test, 1) # reshape for broadcasting
dists -= 2 * np.dot(X, self.X_train.T)
dists = np.sqrt(dists)

In [33]:
a=[0.5,0.1,12,21]
newArray = np.around(a, decimals= -1)
print(newArray)

[ 0.  0. 10. 20.]
