In [180]:
import numpy as np
# Y.row / X.row must be interger
X = [[1,2,3],       # 3 x 3
     [2,3,4],
     [1,2,1]]
Y = [[2,3,4],       
     [4,5,6],
     [2,3,4]]
Y = np.tile(Y,(2,1))    # 6 x 3
X = np.array(X)
dists = np.zeros((3,6))
for i in range(3):
    X_piece = X[[i]]
    X_piece =  np.tile(X_piece,(Y.shape[0],1))
    diff1 = ((X_piece - Y)**2).sum(axis=1)
    # diff2 = diff1.sum(axis= 1)
    dists[i,:] = diff1
print(dists)

[[ 3. 27.  3.  3. 27.  3.]
 [ 0. 12.  0.  0. 12.  0.]
 [11. 43. 11. 11. 43. 11.]]


In [164]:
import numpy as np

arr = np.arange(24).reshape(2,3,4) #生成一个4行5列的数组

print(arr)
# print(arr.T) #求转置
print(arr.transpose((1,0,2)))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
